### ISSUE TITLE
Docker Image ARM architecture

### ISSUE THREAD

**Issue by egvimo** [kibitzr/kibitzr#109]
It would be nice to use the Docker Image on the ARM platform.

Here is an example how that could be done via GitHub Actions:

```yaml
name: Build Docker Image

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: peterdemin/kibitzr:latest,peterdemin/kibitzr:${GITHUB_REF/refs\/tags\//}
```

---

PS: You mentioned that Travis CI is not working anymore. Maybe you could switch to GitHub Actions altogether.
