### ISSUE TITLE
Make smtp notifier configuration work with single recipient

### ISSUE THREAD

**Issue by peterdemin** [kibitzr/kibitzr#11]
Notifier configuration should look like
```
smtp: <you email here@gmail.com>
```
instead of
```
 smtp:
            recipients:
              - <you email here@gmail.com>
            subject: JetPack update
```
subject should be taken from conf's name.
