### ISSUE TITLE
Human-friendly changes

### ISSUE THREAD

**Issue by peterdemin** [kibitzr/kibitzr#14]
Email content to be in human readable form. Like the email I got is like:
```
Jetpack Updates at 'URL'
+++ b/content
@@ -0,0 +1 @@
+Download Version 4.6
```
Now here, won't be it great like email content may show:

```
Jetpack Updates at 'URL'
Previous Value:
Download Version X.X
New Value:
Download Version X.X
```

**Comment by luckyankit** [comment]
Awaiting this update eagerly.. :)

**Comment by peterdemin** [comment]
Just released 2.6.0 with this feature. You'll need to change your kibitzr.yml by replacing
```yaml
      - changes
```
with
```yaml
      - changes: verbose
```
Here is example file for JetPack:
```yaml
pages:

  - name: JetPack updates
    url: https://wordpress.org/plugins/jetpack/
    transform:
        - css: "#plugin-description > div > p > a"
        - text
        - changes: verbose
    notify:
        - smtp:
            recipients:
                - me@gmail.com
            subject: JetPack update
    period: 3600
```

And here is the e-mail:
```
JetPack update

Previous value:
Download Version 4.6
New value:
Download Version 4.7
```
