### ISSUE TITLE
Some html transformations are crashing docker process

### ISSUE THREAD

**Issue by mcrozz** [kibitzr/kibitzr#144]
Seems like all html transformations are broken in the latest docker image (7.0.10). To reproduce, may use next config:

```yaml
checks:
  - name: Test
    url: https://travis-ci.org/kibitzr/kibitzr
    transform:
      - text
      - changes
    notify:
      - python: print(content)
```

And docker-compose config,
```yaml
services:
  kibitzr:
    container_name: kibitzr
    image: peterdemin/kibitzr:latest
    command: '--log-level=debug run'
    volumes:
      - './kibitzr.yml:/root/kibitzr.yml:ro'
    network_mode: 'host'
```

<details><summary>Logs</summary>
<pre>

kibitzr  | 2024-05-09 10:42:48,956 [DEBUG] kibitzr.conf: Loading credentials from /root/kibitzr-creds.yml
kibitzr  | 2024-05-09 10:42:48,962 [DEBUG] kibitzr.conf: Loading settings from /root/kibitzr.yml
kibitzr  | 2024-05-09 10:42:49,011 [INFO] kibitzr.fetcher.loader: Fetching Test at https://travis-ci.org/kibitzr/kibitzr
kibitzr  | 2024-05-09 10:42:49,012 [DEBUG] cachecontrol.controller: Looking up "https://travis-ci.org/kibitzr/kibitzr" in the cache
kibitzr  | 2024-05-09 10:42:49,013 [DEBUG] cachecontrol.controller: No cache entry available
kibitzr  | 2024-05-09 10:42:49,013 [DEBUG] urllib3.connectionpool: Starting new HTTPS connection (1): travis-ci.org:443
kibitzr  | 2024-05-09 10:42:49,447 [DEBUG] urllib3.connectionpool: https://travis-ci.org:443 "GET /kibitzr/kibitzr HTTP/1.1" 301 167
kibitzr  | 2024-05-09 10:42:49,448 [DEBUG] cachecontrol.controller: Updating cache with response from "https://travis-ci.org/kibitzr/kibitzr"
kibitzr  | 2024-05-09 10:42:49,448 [DEBUG] cachecontrol.controller: Caching permanent redirect
kibitzr  | 2024-05-09 10:42:49,451 [DEBUG] cachecontrol.controller: Looking up "https://app.travis-ci.com/kibitzr/kibitzr" in the cache
kibitzr  | 2024-05-09 10:42:49,451 [DEBUG] cachecontrol.controller: No cache entry available
kibitzr  | 2024-05-09 10:42:49,453 [DEBUG] urllib3.connectionpool: Starting new HTTPS connection (1): app.travis-ci.com:443
kibitzr  | 2024-05-09 10:42:50,266 [DEBUG] urllib3.connectionpool: https://app.travis-ci.com:443 "GET /kibitzr/kibitzr HTTP/1.1" 200 None
kibitzr  | 2024-05-09 10:42:50,404 [DEBUG] cachecontrol.controller: Updating cache with response from "https://app.travis-ci.com/kibitzr/kibitzr"
kibitzr  | 2024-05-09 10:42:50,404 [DEBUG] cachecontrol.controller: Caching b/c of expires header. expires in None seconds
kibitzr exited with code 132

</pre>
</details>
