### ISSUE TITLE
Credentials from environment variables extension

### ISSUE THREAD

**Issue by peterdemin** [kibitzr/kibitzr#37]
Create an extension, like [kibitzr-keyring](https://github.com/kibitzr/kibitzr_keyring) that will add `env` key to `creds` dictionary.
Example usage from Python code:
```
creds['env']['AWS_SECRET_KEY']
```
Or in Jinja template:
```
{{ creds.env.AWS_SECRET_KEY }}
```

**Comment by jeverling** [comment]
I think what would actually be even nicer, is when the yaml parser would interpolate environment variables.
So you could define the credentials in `kibitzr-creds.yml` like this:

```yaml
service:
  username: ${KIBITZR_PROJECTNAME_USERNAME}
  password: ${KIBITZR_PROJECTNAME_PASSWORD}
```

This would give you a very easy way to use environment variables without having to use/create an extension.
