### ISSUE TITLE
Add persistent key-value storage

### ISSUE THREAD

**Issue by peterdemin** [kibitzr/kibitzr#41]
It must be global - all keys accessible from all checks.
It must persist between restarts (saved on disk).
Writes should be made in notify:
```yaml
checks:
  - name: Add to stash
    script: echo "Good"
    notify:
      - stash:
          Hubert: {{ content }} news, everyone! 
```
stash notifier accepts dictionary, where each value is a Jinja template.
All keys are written atomically, e.g. if an error happens in one, none will be written.
Stash should be accessible wherever conf is (fetchers, transforms, notifiers) and should be named `stash`.

It will unlock checks aggregation.
