### ISSUE TITLE
Support cron syntax for checks

### ISSUE THREAD

**Issue by peterdemin** [kibitzr/kibitzr#45]
It's nice to have more control over times of checks, than just `period`.
This feature should add alternative `cron` schedule:
```
checks:
  - name: xxx
    cron: 43 21 * * *
```
where space-separated fields account for: minutes, hours, a day of the month, month, a day of the week.

**Comment by akileos** [comment]
https://github.com/josiahcarlson/parse-crontab seems to be a good start. Any opinion before I give a look ?

    ... entry = CronTab('25 * * * *')
    >>> # find the delay from when this was run (around 11:13AM)
    ... entry.next()
    720.81637899999998

**Comment by peterdemin** [comment]
I would be a great feature once implemented. I'm not sure if two schedulers will cooperate.
I would try to use `entry.next()` to add a new single point for `schedule`.

**Comment by cescobarresi** [comment]
I also think there are many use cases for a more detailed timing that the current ``period``, but I'm afraid a full [CRON expression](https://en.wikipedia.org/wiki/Cron#CRON_expression) it's an over kill.
That said I really would like to be able to set a more complex schedule than ``period`` and the ``schedule`` library being used supports this.

I can think of this of approaches: 
**1. Parse the full cron notation** and create as many Jobs as the notation requires in [``app.py:schedule_checks(checkers)``](https://github.com/kibitzr/kibitzr/blob/master/kibitzr/app.py#L136)

**2. Parse a limited cron notation** and create as many Jobs as the notation requires in [``app.py:schedule_checks(checkers)``](https://github.com/kibitzr/kibitzr/blob/master/kibitzr/app.py#L136)

**3. Expose more ``schedule`` feature** by extending the available YAML and let the user define a more complex scheduling. It could start as small increment over the available ``period`` by adding ``every``, ``unit`` and ``at``. 
Something like:
```
checks:
  ...
     period:
        every: 5
        unit: minutes
  ...
     period:
        every: monday
        at: "13:35"
  ...
     period:
        every: 2
        unit: day
        at: "8:30"
```

Without complicating the code too much it could be allowed to setup more than one ``period`` per check and let the user figure out the best way to set up his schedule.

I personally prefer option **3** and could see my self implementing it.

**Comment by peterdemin** [comment]
I like your idea. However I think, it should go under a different key: `schedule` (instead of `period`). Then, if both `schedule` and `period` are present, both should be used.
And later, if `cron` syntax is added, it will go under `cron` key.

**Comment by peterdemin** [comment]
Yes, I want to leave `period` as is. From the language point, `period: 5 minutes` is more readable than `schedule: 5 minutes`. YAML won't allow having multiple `schedule` keys, but `schedule`'s value can be a list. With a shortcut for a single value.

```yaml
checks:
  ...
  schedule:
        every: 2
        unit: day
        at: "8:30"

  ...
  schedule:
      - every: monday
        at: "8:30"
      - every: tuesdays
        at: "9:30"
```
