### ISSUE TITLE
Local SMTP server.

### ISSUE THREAD

**Issue by virtadpt** [kibitzr/kibitzr#46]
OS: Arch Linux, 20170510 patchlevel
Details: Working local installation of Postfix to send and receive e-mail using SMTP(S) automatically; no credentials required, if it's coming from localhost it gets picked up by the mailer and transmitted.  Known to work because it's been running since the server was built a few years ago.

- Successfully installed Kibitzr into a virtualenv
- Configured a JSON feed

```
  - name: Antarctica Starts Here JSON feed
    url: https://drwho.virtadpt.net/json/feed.json
    transform:
      - jq: ".items[0] | { title: .title, url: .url, body: .content_html }"
      - text
      - changes
    notify:
      - smtp: me@example.com
    period: 5
```
- Set up SMTP in kibitzr-creds.yml for what should be a "fire and forget" local SMTP server:

```
smtp:
  host: localhost
  port: 25
```

- Ran Kibitzr: `kibitzr once`
- Nothing.

Is there a way to configure Kibitzr such that it can "just use" a local SMTP server if one is present?
